### ISSUE TITLE
Add authorization

### ISSUE THREAD

**Issue by alaatm** [alaatm/Sejil#2]
Enable auth for Sejil front-end by username, role and maybe auth policies. This should be configurable via code and UI.

**Comment by cnlogistics** [comment]
How to enable authorization?

**Comment by alaatm** [comment]
> 
> 
> How to enable authorization?

Sorry, this is not implemented yet.

**Comment by cnlogistics** [comment]
@alaatm Nice tool anyway , will definitely try it
