### ISSUE TITLE
Using other Log Providers

### ISSUE THREAD

**Issue by kooshan** [alaatm/Sejil#5]
Hi,
thank you for this gorgeous piece of software. I'm promoting this left and right to my colleagues. However, I would very much love to use other log providers, specially Serilog's providers, e.g. Elasticsearch, to be able to have a long term analytical log storage. Is it possible to also use other log providers along side Sejil?

I'm configuring my Serilog providers at `WebHostBuilder` level, just like Sejil, but it is not capturing any of Controller level logs. Although some middleware logs, like my ExceptionHandler and CodePageHandler logs make their way into Serilog's configured providers. 

I'm not sure if this is by design or I'm messing something up.

**Comment by alaatm** [comment]
@kooshan Thank you for your kind words.

Currently, Sejil doesn't work if you configure other Serilog providers. This is something that I would like to change though and would like to make it work with other providers. I have no time frame for this change but its on my priority list.
